### ISSUE TITLE
Rclone configuration location (old to new)

### ISSUE THREAD

**Issue by crespire** [dadatuputi/bwgc_backup#2]
I've finally gotten around to swapping to the new multi-repo setup and things went off without a hitch, mostly. I had to re-configure `rclone` but kept getting `read only` during the configuration, and ran the two commands in the wiki, but still had some issues.

I ended up adding a symbolic link inside `~/bitwarden_gcloud/bitwarden` like so: `rclone.conf -> rclone/rclone.conf` ![image](https://github.com/dadatuputi/bwgc_backup/assets/36272822/3d9ed6a2-94f8-489f-befd-eea12fb44f64)

This restored my previous configuration, and my test backup was successful without any issues. I haven't dived into it yet, but if I have the config in the new location, not sure why it was trying to write to the old location.

**Comment by dadatuputi** [comment]
Thanks @crespire for the feedback. I wonder if it's an issue with the file permissions that needs to be updated as well. Would you be willing to add a note to the wiki around [here](https://github.com/dadatuputi/bitwarden_gcloud/wiki/Backup#troubleshooting-rclone-creation), if it makes sense? Or even just a link to this issue would be fine I think. That way if someone else has a similar problem they can come here and re-open the issue.
