### ISSUE TITLE
Backup of config.json

### ISSUE THREAD

**Issue by asardaes** [dadatuputi/bwgc_backup#3]
I think the `echo` part of this line is referencing the wrong file, probably a copy-paste typo.

https://github.com/dadatuputi/bwgc_backup/blob/2ed75d92a1bce2bfcc91dd2e1b7d7f533e51c853/scripts/backup.sh#L121

**Comment by dadatuputi** [comment]
Great catch, you're right. Fixing and testing.

**Comment by dadatuputi** [comment]
Tested, new script is deployed. You'll need to `docker-compose pull` and `docker-compose up -d` to get the new image. I don't have a `config.json` in my config, so I can't confirm that it's included in the backup.
