### ISSUE TITLE
Rclone sync to GCP bucket fails with uniform bucket-level access enabled

### ISSUE THREAD

**Issue by joshuamsmith** [dadatuputi/bwgc_backup#5]
"Buckets that are set to "Bucket Policy Only" will not accept files being copied into them, since rclone attempts to set an object level ACL."

The resolution requires the "--gcs-bucket-policy-only" flag be added to the sync command line.

        ERR=$(rclone --gcs-bucket-policy-only --config $BACKUP_RCLONE_CONF sync $BACKUP_DIR "$REMOTE$BACKUP_RCLONE_DEST" 2>&1)

**Comment by dadatuputi** [comment]
You can add this flag to your config file instead of the command line, see here:

https://rclone.org/googlecloudstorage/#gcs-bucket-policy-only

For example, 

```
[your-remote-name]
type = google cloud storage
bucket_policy_only = true
# ... other config options
```
